# Generated by Django 5.2.14 on 2026-05-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('IT', 'IT Support'), ('HR', 'Human Resources'), ('FACILITIES', 'Facilities')], default='GENERAL', max_length=30)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags. Example: password, login, vpn', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='faqs_faq_categor_35f6d4_idx'), models.Index(fields=['is_active'], name='faqs_faq_is_acti_575f3a_idx'), models.Index(fields=['question'], name='faqs_faq_questio_2ed515_idx')],
            },
        ),
    ]
