# Generated by Django 5.2.14 on 2026-05-31 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketaiclassification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAgentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_summary', models.TextField(blank=True)),
                ('priority_reason', models.TextField(blank=True)),
                ('sentiment_explanation', models.TextField(blank=True)),
                ('suggested_reply', models.TextField()),
                ('suggested_steps', models.TextField(blank=True)),
                ('escalation_suggestion', models.TextField(blank=True)),
                ('related_kb_articles', models.JSONField(blank=True, default=list)),
                ('similar_tickets', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_agent_suggestions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_suggestions', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
