# Generated by Django 5.2.14 on 2026-06-02 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketagentsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfeedback',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_ticket_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ticketfeedback',
            index=models.Index(fields=['rating'], name='tickets_tic_rating_8dc00b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketfeedback',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_a7c1e7_idx'),
        ),
    ]
